/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Register
     * @description Register a new user account.
     *
     *     Requires a valid registration code to prevent unauthorized registrations.
     *     Returns an access token immediately upon successful registration.
     */
    post: operations['register_auth_register_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login
     * @description OAuth2 compatible token endpoint.
     *
     *     Use this endpoint with the 'Authorize' button in SwaggerUI:
     *     1. Click 'Authorize'
     *     2. Enter your username and password
     *     3. All protected endpoints will be automatically authenticated
     *
     *     This endpoint follows the OAuth2 Password Flow specification.
     */
    post: operations['login_auth_token_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Me
     * @description Get the currently authenticated user's information.
     *
     *     Requires a valid Bearer token in the Authorization header.
     */
    get: operations['get_me_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/auth/change-password': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Change Password
     * @description Change the current user's password.
     *
     *     Requires:
     *     - Valid Bearer token
     *     - Current password (for verification)
     *     - New password (must be different from current)
     */
    post: operations['change_password_auth_change_password_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List All Users
     * @description List all users in the system.
     *
     *     Only ADMIN users can access this endpoint.
     */
    get: operations['list_all_users_admin_users_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/users/{user_id}/role': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update User Role
     * @description Update a user's role.
     *
     *     Only ADMIN users can access this endpoint.
     *     Allows changing a user's role between ADMIN and USER.
     */
    patch: operations['update_user_role_admin_users__user_id__role_patch'];
    trace?: never;
  };
  '/admin/users/{user_id}/invite-limit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Invite Limit
     * @description Update a user's invite code limit.
     *
     *     Only ADMIN users can access this endpoint.
     *     Sets how many active (unused, non-expired) invite codes a user can have.
     */
    patch: operations['update_invite_limit_admin_users__user_id__invite_limit_patch'];
    trace?: never;
  };
  '/admin/codes/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Registration Code
     * @description Generate a new registration code (admin only).
     *
     *     Prefer using POST /codes/generate which is available to all users.
     *     The code will expire after the specified number of hours (default: 24).
     */
    post: operations['generate_registration_code_admin_codes_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/admin/codes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Registration Codes
     * @description List all registration codes (used and unused).
     *
     *     Only ADMIN users can access this endpoint.
     *     Prefer using GET /codes which shows user-specific codes.
     */
    get: operations['list_registration_codes_admin_codes_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/codes/generate': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Generate Code
     * @description Generate a new invite code.
     *
     *     All authenticated users can generate codes.
     *     Non-admin users are limited to their `max_invite_codes` active codes.
     */
    post: operations['generate_code_codes_generate_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/codes/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Codes
     * @description List invite codes.
     *
     *     - Regular users: see only their own codes
     *     - Admins: see all codes
     */
    get: operations['list_codes_codes__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/codes/{code_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Code
     * @description Delete an unused invite code.
     *
     *     - Regular users can only delete their own unused codes.
     *     - Admins can delete any unused code.
     *     - Used codes cannot be deleted (history preservation).
     */
    delete: operations['delete_code_codes__code_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Instances
     * @description List instances — admin sees all, users see their own.
     */
    get: operations['list_instances_instances__get'];
    put?: never;
    /**
     * Create Instance
     * @description Create a new instance (DB record only, no container started).
     */
    post: operations['create_instance_instances__post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Instance */
    get: operations['get_instance_instances__instance_id__get'];
    put?: never;
    post?: never;
    /**
     * Delete Instance
     * @description Stop container (if running), delete DB record and data directory.
     */
    delete: operations['delete_instance_instances__instance_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/start': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start Instance
     * @description Start the Docker container for an instance.
     */
    post: operations['start_instance_instances__instance_id__start_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/stop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Stop Instance
     * @description Stop the container. Blocks until fully stopped.
     */
    post: operations['stop_instance_instances__instance_id__stop_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Instance Status
     * @description Live-check container status against Docker runtime, then return DB state.
     */
    get: operations['instance_status_instances__instance_id__status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/logs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Stream Logs
     * @description SSE endpoint — streams instance logs in real-time via docker logs.
     *     Pass full=true to load the entire log history instead of the last `tail` lines.
     *
     *     The DB session is intentionally closed before streaming starts so that no
     *     connection-pool slot is held for the (potentially unbounded) stream duration.
     *
     *     curl:  curl -N -H "Authorization: Bearer <token>" http://localhost:8000/api/instances/{id}/logs
     */
    get: operations['stream_logs_instances__instance_id__logs_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/streamers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Streamers
     * @description Get the streamer list for a V2 instance.
     */
    get: operations['get_streamers_instances__instance_id__streamers_get'];
    /**
     * Update Streamers
     * @description Update the streamer list. Restart the instance for changes to take effect.
     */
    put: operations['update_streamers_instances__instance_id__streamers_put'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/points': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Instance Points Route
     * @description Latest channel points per streamer for a V2 instance.
     */
    get: operations['get_instance_points_route_instances__instance_id__points_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/instances/{instance_id}/ui': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    get: operations['proxy_http_get_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    put: operations['proxy_http_put_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    post: operations['proxy_http_post_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    delete: operations['proxy_http_delete_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    options: operations['proxy_http_options_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    head: operations['proxy_http_head_root'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    patch: operations['proxy_http_patch_root'];
    trace?: never;
  };
  '/instances/{instance_id}/ui/{path}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    get: operations['proxy_http_get'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    put: operations['proxy_http_put'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    post: operations['proxy_http_post'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    delete: operations['proxy_http_delete'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    options: operations['proxy_http_options'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    head: operations['proxy_http_head'];
    /**
     * Proxy Http
     * @description Proxy HTTP requests to the Docker container's web UI.
     */
    patch: operations['proxy_http_patch'];
    trace?: never;
  };
  '/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Root */
    get: operations['root__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Health */
    get: operations['health_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Body_login_auth_token_post */
    Body_login_auth_token_post: {
      /** Grant Type */
      grant_type?: string | null;
      /** Username */
      username: string;
      /**
       * Password
       * Format: password
       */
      password: string;
      /**
       * Scope
       * @default
       */
      scope: string;
      /** Client Id */
      client_id?: string | null;
      /**
       * Client Secret
       * Format: password
       */
      client_secret?: string | null;
    };
    /** ChangePasswordRequest */
    ChangePasswordRequest: {
      /** Current Password */
      current_password: string;
      /** New Password */
      new_password: string;
    };
    /** GenerateCodeRequest */
    GenerateCodeRequest: {
      /**
       * Expires In Hours
       * @default 24
       */
      expires_in_hours: number;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** InstanceCreate */
    InstanceCreate: {
      /** @default TwitchDropsMiner */
      miner_type: components['schemas']['MinerType'];
      /** Twitch Username */
      twitch_username?: string | null;
      /**
       * Streamers
       * @default []
       */
      streamers: string[];
    };
    /** InstanceResponse */
    InstanceResponse: {
      /** Id */
      id: string;
      /** User Id */
      user_id: string;
      miner_type: components['schemas']['MinerType'];
      status: components['schemas']['InstanceState'];
      /** Container Id */
      container_id?: string | null;
      /** Port */
      port?: number | null;
      /** Ui Url */
      ui_url?: string | null;
      /** Twitch Username */
      twitch_username?: string | null;
      /** Activation Code */
      activation_code?: string | null;
      /** Activation Url */
      activation_url?: string | null;
      /**
       * Streamers
       * @default []
       */
      streamers: string[];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Last Started At */
      last_started_at?: string | null;
      /** Last Stopped At */
      last_stopped_at?: string | null;
    };
    /**
     * InstanceState
     * @description Miner instance lifecycle states.
     * @enum {string}
     */
    InstanceState: 'stopped' | 'running' | 'stopping';
    /** InstanceStatus */
    InstanceStatus: {
      /** Id */
      id: string;
      status: components['schemas']['InstanceState'];
      /** Container Id */
      container_id?: string | null;
      /** Port */
      port?: number | null;
      /** Activation Url */
      activation_url?: string | null;
      /** Activation Code */
      activation_code?: string | null;
    };
    /**
     * MinerType
     * @description Miner implementation type.
     * @enum {string}
     */
    MinerType: 'TwitchDropsMiner' | 'TwitchPointsMinerV2';
    /** RegisterRequest */
    RegisterRequest: {
      /** Username */
      username: string;
      /** Password */
      password: string;
      /** Registration Code */
      registration_code: string;
    };
    /** RegistrationCodeDetailResponse */
    RegistrationCodeDetailResponse: {
      /** Id */
      id: string;
      /** Code */
      code: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Used At */
      used_at: string | null;
      /** Used By */
      used_by: string | null;
      /** Created By Username */
      created_by_username?: string | null;
      /** Is Valid */
      is_valid: boolean;
    };
    /** RegistrationCodeResponse */
    RegistrationCodeResponse: {
      /** Code */
      code: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
    };
    /** StreamerPointsSnapshot */
    StreamerPointsSnapshot: {
      /** Streamer */
      streamer: string;
      /** Channel Points */
      channel_points: string | null;
    };
    /** StreamersUpdate */
    StreamersUpdate: {
      /** Streamers */
      streamers: string[];
    };
    /** TokenResponse */
    TokenResponse: {
      /** Access Token */
      access_token: string;
      /**
       * Token Type
       * @default bearer
       */
      token_type: string;
      /** User Id */
      user_id: string;
      /** Username */
      username: string;
    };
    /** UpdateInviteLimitRequest */
    UpdateInviteLimitRequest: {
      /** Max Invite Codes */
      max_invite_codes: number;
    };
    /** UpdateUserRoleRequest */
    UpdateUserRoleRequest: {
      role: components['schemas']['UserRole'];
    };
    /** UserResponse */
    UserResponse: {
      /** Id */
      id: string;
      /** Username */
      username: string;
      role: components['schemas']['UserRole'];
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Max Invite Codes
       * @default 2
       */
      max_invite_codes: number;
    };
    /**
     * UserRole
     * @description User role enumeration.
     * @enum {string}
     */
    UserRole: 'admin' | 'user';
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  register_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  login_auth_token_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/x-www-form-urlencoded': components['schemas']['Body_login_auth_token_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['TokenResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
    };
  };
  change_password_auth_change_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ChangePasswordRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_all_users_admin_users_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'][];
        };
      };
    };
  };
  update_user_role_admin_users__user_id__role_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateUserRoleRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_invite_limit_admin_users__user_id__invite_limit_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        user_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateInviteLimitRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  generate_registration_code_admin_codes_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateCodeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegistrationCodeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_registration_codes_admin_codes_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegistrationCodeDetailResponse'][];
        };
      };
    };
  };
  generate_code_codes_generate_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GenerateCodeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegistrationCodeResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_codes_codes__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RegistrationCodeDetailResponse'][];
        };
      };
    };
  };
  delete_code_codes__code_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        code_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_instances_instances__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceResponse'][];
        };
      };
    };
  };
  create_instance_instances__post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['InstanceCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_instance_instances__instance_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_instance_instances__instance_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  start_instance_instances__instance_id__start_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stop_instance_instances__instance_id__stop_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  instance_status_instances__instance_id__status_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['InstanceStatus'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  stream_logs_instances__instance_id__logs_get: {
    parameters: {
      query?: {
        tail?: number;
        full?: boolean;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_streamers_instances__instance_id__streamers_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_streamers_instances__instance_id__streamers_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StreamersUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_instance_points_route_instances__instance_id__points_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamerPointsSnapshot'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_get_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_put_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_post_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_delete_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_options_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_head_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_patch_root: {
    parameters: {
      query?: {
        path?: string;
      };
      header?: never;
      path: {
        instance_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_options: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_head: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  proxy_http_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        instance_id: string;
        path: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
}
